### ISSUE TITLE
Saving SD info to images

### ISSUE THREAD

**Issue by Automaticism** [d3x-at/sd-parsers#1]
Would it be an idea to have the ability to save SD info to images? 
Could have it save by which parser you choose?

I've been considering adding that to Promptvision, but your idea of using this as a lib is much better.

**Comment by d3x-at** [comment]
Having looked at your project, i am not sure what exactly you are trying to do, so feel free to correct me when i am going into the wrong direction with this answer.

Generally, i don't see much benefit in adding saving functionality to my library, as the Pillow library handles this pretty well already. Mixing in the sd-parsers library into this is also not a problem, as you can see in the example below:

```python
from PIL import Image
from PIL.PngImagePlugin import PngInfo
from sdparsers import ParserManager

parser = ParserManager()

with Image.open("test.png") as image:
    # read data here
    data = parser.parse(image)
    # do stuff with data
    ....

    # then write some data
    if image.format == "PNG":
        png_info = PngInfo()

        # add the metadata from the opened image
        for key, value in image.text.items():
            png_info.add_text(key, value)

        # then add your custom key
        png_info.add_text("my-custom-key", "my-custom-value")

        # save
        image.save("test_out.png", png_info=png_info)
```

I personally though, would advise against writing metadata back into images in any form if you can avoid it, as (as with any file operation) there is always the chance of something going wrong.
