### ISSUE TITLE
Update import statement in README or refactor code.

### ISSUE THREAD

**Issue by deepratnaawale** [d3x-at/sd-parsers#4]
When using pip to install the package, it is installed as **sdparsers** and not **sd_parsers**. Importing the library now requires sdparsers instead of sd_parsers. Please either refactor code or fix the documentation in **README.md**.

**Comment by d3x-at** [comment]
Installing a 0.3 release candidate (using pip install --upgrade --pre sd-parsers) will fix that for you for the time being.
See the [release notes](https://github.com/d3x-at/sd-parsers/releases/tag/v0.3rc2) for further changes.
